# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publica',
            name='dislike',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publica',
            name='like',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
