# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0002_auto_20151208_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publica',
            name='dislike',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='publica',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
