# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_usuarios_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amigo',
            name='usr2',
            field=models.ManyToManyField(related_name='_amigo_usr2_+', to='cuentas.Amigo'),
        ),
    ]
